name: Weekly Newsletter

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch RSS feeds
        env:
          RSS_FEED_URLS: ${{ secrets.RSS_FEED_URLS }}
        run: python scripts/fetch_rss_feeds.py
      - name: Send newsletter
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_SERVER_PREFIX: ${{ secrets.MAILCHIMP_SERVER_PREFIX }}
          MAILCHIMP_LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_FROM_NAME: ${{ secrets.EMAIL_FROM_NAME }}
          RSS_FEED_URLS: ${{ secrets.RSS_FEED_URLS }}
        run: python scripts/send_newsletter.py
